export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const GET_USERS='GET_USERS';
export const REGISTER_SUCCESS="REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";
